### ISSUE TITLE
Port bindings and Volume bindings dont seem to work

### ISSUE THREAD

**Issue by AnalogJ** [someara/kitchen-dokken#106]
I've tried a couple of different syntaxes while attempting to get this to work:

```
volumes: [
  '/var/lib/docker:/internal/path', '/var/lib/docker-one:/internal/path1, '/var/lib/docker-two:/internal/path2'
  ]
```

```
volumes:
 - '/var/lib/docker:/internal/path'
 - '/var/lib/docker-one:/internal/path1'
 - '/var/lib/docker-two:/internal/path2'
```

Nothing showed up in the `runner_container` section of the generated `.yml` config file, just the defaults:

```
  Volumes:
    "/opt/chef": "/var/lib/docker/volumes/f47c454145704e3072f6b7644e9b6760cd0af134fa8e3d7438ec309797549127/_data"
    "/opt/kitchen": "/var/lib/docker/volumes/8e3d37e150955623b48317ac2df4e369dc4e3dc1d8ceaf2b33697ac1a9e14863/_data"
    "/opt/verifier": "/var/lib/docker/volumes/487ca7b7057d52404ac9ecb653529119865f9b6c80ab8908cdd484c1cc5ec004/_data"
    "[": "/var/lib/docker/volumes/d1eaa45bbecf097440b487a65a4721267d839c74a4ad23542f8b45e18c503272/_data"
    "]": "/var/lib/docker/volumes/bed22c3af13d9e4d819feae51ff45d76b06e12b490eb9c0c67b591f5cbceec53/_data"
  VolumesRW:
    "/opt/chef": true
    "/opt/kitchen": true
    "/opt/verifier": true
    "[": true
    "]": true
```

**Comment by rmoriz** [comment]
see the main Readme for a correct YAML example (search for systemd)

**Comment by AnalogJ** [comment]
Hey @rmoriz 

Thanks for the pointer but I tried that as well. Didn't work. 

```
    volumes:
      - /tmp/directory:/tmp_directory:ro
```

**Comment by rmoriz** [comment]
@AnalogJ yes. https://github.com/rabbitmq/chef-cookbook/blob/master/.kitchen.dokken.yml#L6

**Comment by missett** [comment]
I managed to get bind mounting working for myself using the 'binds' config instead of 'volumes'. So I ended up with something that looked like this (can't post the exact snippet unfortunately).

`driver:
  name: dokken
  chef_version: 12.11.18
  privileged: true
  binds:
   - /my/host/directory:/mnt`

I had to reference the dokken source to figure it out, not sure why it's 'binds' instead of 'volumes' like the other drivers.

**Comment by wjordan** [comment]
Seems this was an issue in older versions of `kitchen-dokken` but was fixed in recent versions.

I had inadvertently installed `kitchen-dokken` v1.0.5 (due to locking `test-kitchen` to 1.5.0), and experienced this issue. (Using `binds` config instead of `volumes` worked). Upgrading both `test-kitchen` and `kitchen-dokken` to the latest (currently 1.19.0 and 2.6.5 respectively) fixed the issue for me.

**Comment by tas50** [comment]
Closing this out since it looks like it was resolved
